// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class FinishedGoodsItems
{
    public int logId { get; set; }

    public int itemId { get; set; }

    public decimal targetQuantity { get; set; }

    public decimal actualQuantity { get; set; }

    public string reasonForDiff { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public string itemName { get; set; }
    
}