// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class BillItemsDetails
{
    public int itemId { get; set; }

    public string itemName { get; set; }

    public string unit { get; set; }

    public decimal? pricePerUnit { get; set; }

    public decimal? priceQuantity { get; set; }

    public int fkBillOrderId { get; set; }

    public int fkItemId { get; set; }

    public int quantity { get; set; }

    public decimal price { get; set; }

    public decimal maxQuantity { get; set; }

}