// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class ItemMasterView
{
    public int itemId { get; set; }

    public string itemName { get; set; }

    public string itemDescription { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public string itemType { get; set; }

    public string unit { get; set; }

    public decimal? pricePerUnit { get; set; }

    public int? fkCategoryId { get; set; }

    public decimal? priceQuantity { get; set; }

    public string categeoryName { get; set; }
}