// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Billing
{
    public int billId { get; set; }

    public int? fkOrderId { get; set; }

    public int? fkCustomerId { get; set; }

    public string paymentMode { get; set; }

    public decimal? discount { get; set; }

    public decimal? taxAmount { get; set; }

    public decimal finalAmount { get; set; }

    public string paymentStatus { get; set; }

    public DateTime billDate { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public decimal? advanceAmount { get; set; }

    public virtual Customers fkCustomer { get; set; }

    public virtual Orders fkOrder { get; set; }
}