// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class BusinessAnalytics
{
    public int analyticsId { get; set; }

    public DateOnly analyticsDate { get; set; }

    public string metricName { get; set; }

    public string metricCategory { get; set; }

    public decimal? metricValue { get; set; }

    public string metricUnit { get; set; }

    public int? relatedListingId { get; set; }

    public DateTime? calculatedDate { get; set; }

    public virtual CarListings relatedListing { get; set; }
}