// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class BusinessAnalytics
{
    public int AnalyticsId { get; set; }

    public DateOnly AnalyticsDate { get; set; }

    public string MetricName { get; set; }

    public string MetricCategory { get; set; }

    public decimal? MetricValue { get; set; }

    public string MetricUnit { get; set; }

    public int? RelatedListingId { get; set; }

    public DateTime? CalculatedDate { get; set; }

    public virtual CarListings RelatedListing { get; set; }
}