// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarBrands
{
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public string BrandCountryOfOrigin { get; set; }

    public string BrandLogo { get; set; }

    public string BrandWebsite { get; set; }

    public bool? IsLuxuryBrand { get; set; }

    public bool? IsActiveBrand { get; set; }

    public DateTime? BrandCreatedDate { get; set; }

    public string BrandNotes { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<CarModels> CarModels { get; set; } = new List<CarModels>();
}