// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarBrands
{
    public int brandId { get; set; }

    public string brandName { get; set; }

    public string brandCountryOfOrigin { get; set; }

    public string brandLogo { get; set; }

    public string brandWebsite { get; set; }

    public bool? isLuxuryBrand { get; set; }

    public bool? isActiveBrand { get; set; }

    public DateTime? brandCreatedDate { get; set; }

    public string brandNotes { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<CarModels> CarModels { get; set; } = new List<CarModels>();
}