// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarConditionLevels
{
    public int conditionId { get; set; }

    public string conditionName { get; set; }

    public string conditionDescription { get; set; }

    public int? conditionPercentage { get; set; }

    public decimal? expectedPriceReduction { get; set; }

    public string typicalIssues { get; set; }

    public string recommendedFor { get; set; }

    public int? conditionSortOrder { get; set; }

    public bool? isActiveCondition { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}