// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarConditionLevels
{
    public int ConditionId { get; set; }

    public string ConditionName { get; set; }

    public string ConditionDescription { get; set; }

    public int? ConditionPercentage { get; set; }

    public decimal? ExpectedPriceReduction { get; set; }

    public string TypicalIssues { get; set; }

    public string RecommendedFor { get; set; }

    public int? ConditionSortOrder { get; set; }

    public bool? IsActiveCondition { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}