// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarColors
{
    public int colorId { get; set; }

    public string colorName { get; set; }

    public string colorDisplayName { get; set; }

    public string colorHexCode { get; set; }

    public string colorFamily { get; set; }

    public bool? isMetallicPaint { get; set; }

    public bool? isPearlPaint { get; set; }

    public bool? isSolidPaint { get; set; }

    public int? popularityRank { get; set; }

    public string resaleValueImpact { get; set; }

    public bool? isActiveColor { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}