// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarColors
{
    public int ColorId { get; set; }

    public string ColorName { get; set; }

    public string ColorDisplayName { get; set; }

    public string ColorHexCode { get; set; }

    public string ColorFamily { get; set; }

    public bool? IsMetallicPaint { get; set; }

    public bool? IsPearlPaint { get; set; }

    public bool? IsSolidPaint { get; set; }

    public int? PopularityRank { get; set; }

    public string ResaleValueImpact { get; set; }

    public bool? IsActiveColor { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}