// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarFeaturesList
{
    public int FeatureId { get; set; }

    public string FeatureName { get; set; }

    public string FeatureDisplayName { get; set; }

    public string FeatureCategory { get; set; }

    public string FeatureSubCategory { get; set; }

    public string FeatureDescription { get; set; }

    public string FeatureImportanceLevel { get; set; }

    public string TypicalFoundIn { get; set; }

    public bool? AffectsResaleValue { get; set; }

    public bool? IsStandardFeature { get; set; }

    public bool? IsActiveFeature { get; set; }

    public string FeatureIcon { get; set; }

    public virtual ICollection<CarListingFeatures> CarListingFeatures { get; set; } = new List<CarListingFeatures>();
}