// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarImages
{
    public int imageId { get; set; }

    public int listingId { get; set; }

    public string imageFileName { get; set; }

    public string imageFilePath { get; set; }

    public long? imageFileSize { get; set; }

    public string imageType { get; set; }

    public string imageCategory { get; set; }

    public string imageDescription { get; set; }

    public bool? isPrimaryImage { get; set; }

    public bool? isWatermarked { get; set; }

    public int? imageSortOrder { get; set; }

    public DateTime? imageUploadDate { get; set; }

    public string imageQuality { get; set; }

    public bool? isActiveImage { get; set; }

    public virtual CarListings listing { get; set; }
}