// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarImages
{
    public int ImageId { get; set; }

    public int ListingId { get; set; }

    public string ImageFileName { get; set; }

    public string ImageFilePath { get; set; }

    public long? ImageFileSize { get; set; }

    public string ImageType { get; set; }

    public string ImageCategory { get; set; }

    public string ImageDescription { get; set; }

    public bool? IsPrimaryImage { get; set; }

    public bool? IsWatermarked { get; set; }

    public int? ImageSortOrder { get; set; }

    public DateTime? ImageUploadDate { get; set; }

    public string ImageQuality { get; set; }

    public bool? IsActiveImage { get; set; }

    public virtual CarListings Listing { get; set; }
}