// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarListingViews
{
    public int ViewId { get; set; }

    public int ListingId { get; set; }

    public DateTime? ViewDate { get; set; }

    public string ViewerIPAddress { get; set; }

    public string ViewerUserAgent { get; set; }

    public string ViewerLocation { get; set; }

    public string ReferrerSource { get; set; }

    public int? TimeSpentInSeconds { get; set; }

    public int? PagesViewed { get; set; }

    public int? ImagesViewed { get; set; }

    public bool? ContactDetailsViewed { get; set; }

    public bool? PhoneNumberRevealed { get; set; }

    public virtual CarListings Listing { get; set; }
}