// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarListingViews
{
    public int viewId { get; set; }

    public int listingId { get; set; }

    public DateTime? viewDate { get; set; }

    public string viewerIPAddress { get; set; }

    public string viewerUserAgent { get; set; }

    public string viewerLocation { get; set; }

    public string referrerSource { get; set; }

    public int? timeSpentInSeconds { get; set; }

    public int? pagesViewed { get; set; }

    public int? imagesViewed { get; set; }

    public bool? contactDetailsViewed { get; set; }

    public bool? phoneNumberRevealed { get; set; }

    public virtual CarListings listing { get; set; }
}