// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarListingFeatures
{
    public int listingFeatureId { get; set; }

    public int listingId { get; set; }

    public int featureId { get; set; }

    public bool? isFeatureAvailable { get; set; }

    public string featureCondition { get; set; }

    public string featureNotes { get; set; }

    public DateTime? featureMappedDate { get; set; }

    public virtual CarFeaturesList feature { get; set; }

    public virtual CarListings listing { get; set; }
}