// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarListingFeatures
{
    public int ListingFeatureId { get; set; }

    public int ListingId { get; set; }

    public int FeatureId { get; set; }

    public bool? IsFeatureAvailable { get; set; }

    public string FeatureCondition { get; set; }

    public string FeatureNotes { get; set; }

    public DateTime? FeatureMappedDate { get; set; }

    public virtual CarFeaturesList Feature { get; set; }

    public virtual CarListings Listing { get; set; }
}