// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarModels
{
    public int ModelId { get; set; }

    public int BrandId { get; set; }

    public string ModelName { get; set; }

    public int? ModelLaunchYear { get; set; }

    public int? ModelDiscontinuedYear { get; set; }

    public string ModelGeneration { get; set; }

    public string ModelBodyType { get; set; }

    public bool? IsActiveModel { get; set; }

    public DateTime? ModelCreatedDate { get; set; }

    public string ModelDescription { get; set; }

    public virtual CarBrands Brand { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<CarVariants> CarVariants { get; set; } = new List<CarVariants>();
}