// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarModels
{
    public int modelId { get; set; }

    public int brandId { get; set; }

    public string modelName { get; set; }

    public int? modelLaunchYear { get; set; }

    public int? modelDiscontinuedYear { get; set; }

    public string modelGeneration { get; set; }

    public string modelBodyType { get; set; }

    public bool? isActiveModel { get; set; }

    public DateTime? modelCreatedDate { get; set; }

    public string modelDescription { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<CarVariants> CarVariants { get; set; } = new List<CarVariants>();

    public virtual CarBrands brand { get; set; }
}