// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarVariants
{
    public int variantId { get; set; }

    public int modelId { get; set; }

    public string variantName { get; set; }

    public string variantTrimLevel { get; set; }

    public decimal? variantLaunchPrice { get; set; }

    public decimal? variantCurrentPrice { get; set; }

    public bool? isActiveVariant { get; set; }

    public DateTime? variantCreatedDate { get; set; }

    public string variantFeatures { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual CarModels model { get; set; }
}