// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CarVariants
{
    public int VariantId { get; set; }

    public int ModelId { get; set; }

    public string VariantName { get; set; }

    public string VariantTrimLevel { get; set; }

    public decimal? VariantLaunchPrice { get; set; }

    public decimal? VariantCurrentPrice { get; set; }

    public bool? IsActiveVariant { get; set; }

    public DateTime? VariantCreatedDate { get; set; }

    public string VariantFeatures { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual CarModels Model { get; set; }
}