// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Category
{
    public int id { get; set; }

    public string categoryName { get; set; }

    public string description { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public string sUser { get; set; }

    public virtual ICollection<InventoryItems> InventoryItems { get; set; } = new List<InventoryItems>();
}