// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CustomerInquiries
{
    public int InquiryId { get; set; }

    public int ListingId { get; set; }

    public string InquiryType { get; set; }

    public string CustomerName { get; set; }

    public string CustomerPhone { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerLocation { get; set; }

    public string InquirySubject { get; set; }

    public string InquiryMessage { get; set; }

    public string BudgetRange { get; set; }

    public bool? FinanceRequired { get; set; }

    public bool? TradeInRequired { get; set; }

    public string PreferredContactMethod { get; set; }

    public DateTime? InquiryDate { get; set; }

    public string InquiryStatus { get; set; }

    public string PriorityLevel { get; set; }

    public string ExpectedPurchaseTimeline { get; set; }

    public DateTime? FirstResponseDate { get; set; }

    public DateTime? LastContactDate { get; set; }

    public string ResponseByUserId { get; set; }

    public string ResponseNotes { get; set; }

    public bool? FollowUpRequired { get; set; }

    public DateTime? NextFollowUpDate { get; set; }

    public bool? ViewedCarPhysically { get; set; }

    public bool? TookTestDrive { get; set; }

    public bool? MadeOffer { get; set; }

    public decimal? OfferedPrice { get; set; }

    public bool? PurchasedCar { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    public decimal? FinalPurchasePrice { get; set; }

    public virtual CarListings Listing { get; set; }
}