// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class CustomerInquiries
{
    public int inquiryId { get; set; }

    public int listingId { get; set; }

    public string inquiryType { get; set; }

    public string customerName { get; set; }

    public string customerPhone { get; set; }

    public string customerEmail { get; set; }

    public string customerLocation { get; set; }

    public string inquirySubject { get; set; }

    public string inquiryMessage { get; set; }

    public string budgetRange { get; set; }

    public bool? financeRequired { get; set; }

    public bool? tradeInRequired { get; set; }

    public string preferredContactMethod { get; set; }

    public DateTime? inquiryDate { get; set; }

    public string inquiryStatus { get; set; }

    public string priorityLevel { get; set; }

    public string expectedPurchaseTimeline { get; set; }

    public DateTime? firstResponseDate { get; set; }

    public DateTime? lastContactDate { get; set; }

    public string responseByUserId { get; set; }

    public string responseNotes { get; set; }

    public bool? followUpRequired { get; set; }

    public DateTime? nextFollowUpDate { get; set; }

    public bool? viewedCarPhysically { get; set; }

    public bool? tookTestDrive { get; set; }

    public bool? madeOffer { get; set; }

    public decimal? offeredPrice { get; set; }

    public bool? purchasedCar { get; set; }

    public DateOnly? purchaseDate { get; set; }

    public decimal? finalPurchasePrice { get; set; }

    public virtual CarListings listing { get; set; }
}