// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Customers
{
    public int customerId { get; set; }

    public string customerName { get; set; }

    public string phoneNo { get; set; }

    public string address { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public virtual ICollection<Billing> Billing { get; set; } = new List<Billing>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}