// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class DailyExpense
{
    public int id { get; set; }

    public DateOnly expenseDate { get; set; }

    public decimal amountGiven { get; set; }

    public string expenseDetails { get; set; }

    public decimal? totalExpenses { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public string sUser { get; set; }

    public decimal amountSpent { get; set; }
}