// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class EngineSpecifications
{
    public int engineSpecId { get; set; }

    public string engineType { get; set; }

    public int? engineCylinders { get; set; }

    public string engineValveConfiguration { get; set; }

    public bool? turbochargedEngine { get; set; }

    public bool? superchargedEngine { get; set; }

    public bool? naturallyAspiratedEngine { get; set; }

    public bool? hybridSystem { get; set; }

    public string engineDescription { get; set; }

    public string performanceRating { get; set; }

    public bool? isActiveEngineSpec { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}