// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class EngineSpecifications
{
    public int EngineSpecId { get; set; }

    public string EngineType { get; set; }

    public int? EngineCylinders { get; set; }

    public string EngineValveConfiguration { get; set; }

    public bool? TurbochargedEngine { get; set; }

    public bool? SuperchargedEngine { get; set; }

    public bool? NaturallyAspiratedEngine { get; set; }

    public bool? HybridSystem { get; set; }

    public string EngineDescription { get; set; }

    public string PerformanceRating { get; set; }

    public bool? IsActiveEngineSpec { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}