// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class FuelTypes
{
    public int FuelTypeId { get; set; }

    public string FuelTypeName { get; set; }

    public string FuelTypeDescription { get; set; }

    public bool? IsEcoFriendly { get; set; }

    public decimal? TypicalFuelPrice { get; set; }

    public string FuelEfficiencyRating { get; set; }

    public string MaintenanceCostLevel { get; set; }

    public string AvailabilityLevel { get; set; }

    public bool? IsActiveFuelType { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}