// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class FuelTypes
{
    public int fuelTypeId { get; set; }

    public string fuelTypeName { get; set; }

    public string fuelTypeDescription { get; set; }

    public bool? isEcoFriendly { get; set; }

    public decimal? typicalFuelPrice { get; set; }

    public string fuelEfficiencyRating { get; set; }

    public string maintenanceCostLevel { get; set; }

    public string availabilityLevel { get; set; }

    public bool? isActiveFuelType { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}