// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class GeographicCities
{
    public int cityId { get; set; }

    public int stateId { get; set; }

    public string cityName { get; set; }

    public string cityType { get; set; }

    public int? cityPopulation { get; set; }

    public bool? hasGoodCarMarket { get; set; }

    public string typicalCarDemand { get; set; }

    public bool? isActiveCity { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<RTOCodes> RTOCodes { get; set; } = new List<RTOCodes>();

    public virtual GeographicStates state { get; set; }
}