// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class GeographicCities
{
    public int CityId { get; set; }

    public int StateId { get; set; }

    public string CityName { get; set; }

    public string CityType { get; set; }

    public int? CityPopulation { get; set; }

    public bool? HasGoodCarMarket { get; set; }

    public string TypicalCarDemand { get; set; }

    public bool? IsActiveCity { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<RTOCodes> RTOCodes { get; set; } = new List<RTOCodes>();

    public virtual GeographicStates State { get; set; }
}