// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class GeographicStates
{
    public int stateId { get; set; }

    public string stateName { get; set; }

    public string stateCode { get; set; }

    public string stateRegion { get; set; }

    public string countryName { get; set; }

    public string statePinCodePrefix { get; set; }

    public bool? popularForCars { get; set; }

    public bool? isActiveState { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<GeographicCities> GeographicCities { get; set; } = new List<GeographicCities>();

    public virtual ICollection<RTOCodes> RTOCodes { get; set; } = new List<RTOCodes>();
}