// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class GeographicStates
{
    public int StateId { get; set; }

    public string StateName { get; set; }

    public string StateCode { get; set; }

    public string StateRegion { get; set; }

    public string CountryName { get; set; }

    public string StatePinCodePrefix { get; set; }

    public bool? PopularForCars { get; set; }

    public bool? IsActiveState { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual ICollection<GeographicCities> GeographicCities { get; set; } = new List<GeographicCities>();

    public virtual ICollection<RTOCodes> RTOCodes { get; set; } = new List<RTOCodes>();
}