// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class InsuranceProviders
{
    public int InsuranceProviderId { get; set; }

    public string ProviderName { get; set; }

    public string ProviderType { get; set; }

    public decimal? ProviderRating { get; set; }

    public decimal? ClaimSettlementRatio { get; set; }

    public string CustomerServiceRating { get; set; }

    public bool? IsActiveProvider { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}