// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class InsuranceProviders
{
    public int insuranceProviderId { get; set; }

    public string providerName { get; set; }

    public string providerType { get; set; }

    public decimal? providerRating { get; set; }

    public decimal? claimSettlementRatio { get; set; }

    public string customerServiceRating { get; set; }

    public bool? isActiveProvider { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}