// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Inventory
{
    public int inventoryID { get; set; }

    public int itemID { get; set; }

    public decimal quantity { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public virtual InventoryItems item { get; set; }
}