// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class InventoryItems
{
    public int itemId { get; set; }

    public string itemName { get; set; }

    public string itemDescription { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public string itemType { get; set; }

    public string unit { get; set; }

    public decimal? pricePerUnit { get; set; }

    public int? fkCategoryId { get; set; }

    public decimal? priceQuantity { get; set; }

    public virtual ICollection<BakedCookedLogs> BakedCookedLogs { get; set; } = new List<BakedCookedLogs>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<ItemsUsedForGoods> ItemsUsedForGoods { get; set; } = new List<ItemsUsedForGoods>();

    public virtual ICollection<PurchaseDetails> PurchaseDetails { get; set; } = new List<PurchaseDetails>();

    public virtual ICollection<ReturnItems> ReturnItemsfkInventoryItem { get; set; } = new List<ReturnItems>();

    public virtual ICollection<ReturnItems> ReturnItemsfkReuseDestianationItem { get; set; } = new List<ReturnItems>();

    public virtual ICollection<ReturnManagement> ReturnManagement { get; set; } = new List<ReturnManagement>();

    public virtual Category fkCategory { get; set; }
}