// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class MasterBranch
{
    public int branchId { get; set; }

    public string displayName { get; set; }

    public string branchAddress { get; set; }

    public string city { get; set; }

    public string pincode { get; set; }

    public string footerMessage { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public string sUser { get; set; }
}