// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class PurchaseDetails
{
    public int purchaseDetailId { get; set; }

    public int fkRawMaterialId { get; set; }

    public int fkItemId { get; set; }

    public decimal quantity { get; set; }

    public string unit { get; set; }

    public decimal pricePerUnit { get; set; }

    public decimal? totalAmount { get; set; }

    public virtual InventoryItems fkItem { get; set; }

    public virtual RawMaterialLogs fkRawMaterial { get; set; }
}