// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Recipe
{
    public int recipeId { get; set; }

    public int fkItemName { get; set; }

    public decimal? baseQuantity { get; set; }

    public string unit { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public string sUser { get; set; }
}