// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class ReturnItems
{
    public int returnItemTblId { get; set; }

    public int? fkInventoryItemId { get; set; }

    public int? quantity { get; set; }

    public string returnReason { get; set; }

    public string returnDescription { get; set; }

    public decimal? returnPrice { get; set; }

    public int fkReturnId { get; set; }

    public string unit { get; set; }

    public decimal discount { get; set; }

    public string ReuseDestination { get; set; }

    public int? fkReuseDestianationItemId { get; set; }

    public virtual InventoryItems fkInventoryItem { get; set; }

    public virtual ReturnManagement fkReturn { get; set; }

    public virtual InventoryItems fkReuseDestianationItem { get; set; }
}