// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class ReturnManagement
{
    public int returnId { get; set; }

    public int itemId { get; set; }

    public string returnDescription { get; set; }

    public DateTime? returnDate { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public string sUser { get; set; }

    public int? fkcotomerID { get; set; }

    public decimal? TotalReturnPrice { get; set; }

    public int? fkReternManagementId { get; set; }

    public virtual ICollection<ReturnManagement> InversefkReternManagement { get; set; } = new List<ReturnManagement>();

    public virtual ICollection<ReturnItems> ReturnItems { get; set; } = new List<ReturnItems>();

    public virtual ReturnManagement fkReternManagement { get; set; }

    public virtual InventoryItems item { get; set; }
}