// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class RTOCodes
{
    public int rtoId { get; set; }

    public string rtoCode { get; set; }

    public string rtoName { get; set; }

    public int stateId { get; set; }

    public int? cityId { get; set; }

    public string rtoAddress { get; set; }

    public string rtoContactNumber { get; set; }

    public bool? isActiveRTO { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual GeographicCities city { get; set; }

    public virtual GeographicStates state { get; set; }
}