// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class RTOCodes
{
    public int RTOId { get; set; }

    public string RTOCode { get; set; }

    public string RTOName { get; set; }

    public int StateId { get; set; }

    public int? CityId { get; set; }

    public string RTOAddress { get; set; }

    public string RTOContactNumber { get; set; }

    public bool? IsActiveRTO { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();

    public virtual GeographicCities City { get; set; }

    public virtual GeographicStates State { get; set; }
}