// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Suppliers
{
    public int supplierId { get; set; }

    public string supplierName { get; set; }

    public string address { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime updatedDate { get; set; }

    public string sUser { get; set; }

    public string phoneNumber { get; set; }

    public string state { get; set; }

    public string city { get; set; }

    public virtual ICollection<RawMaterialLogs> RawMaterialLogs { get; set; } = new List<RawMaterialLogs>();
}