// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class SystemConfiguration
{
    public int configId { get; set; }

    public string configCategory { get; set; }

    public string configKey { get; set; }

    public string configValue { get; set; }

    public string configDescription { get; set; }

    public string configDataType { get; set; }

    public bool? isUserEditable { get; set; }

    public bool? requiresRestart { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? modifiedDate { get; set; }

    public string modifiedByUserId { get; set; }
}