// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class SystemConfiguration
{
    public int ConfigId { get; set; }

    public string ConfigCategory { get; set; }

    public string ConfigKey { get; set; }

    public string ConfigValue { get; set; }

    public string ConfigDescription { get; set; }

    public string ConfigDataType { get; set; }

    public bool? IsUserEditable { get; set; }

    public bool? RequiresRestart { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedByUserId { get; set; }
}