// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class TransmissionTypes
{
    public int TransmissionId { get; set; }

    public string TransmissionName { get; set; }

    public string TransmissionFullName { get; set; }

    public string TransmissionDescription { get; set; }

    public string EaseOfDriving { get; set; }

    public string FuelEfficiencyImpact { get; set; }

    public string MaintenanceCost { get; set; }

    public bool? IsActiveTranmission { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}