// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class TransmissionTypes
{
    public int transmissionId { get; set; }

    public string transmissionName { get; set; }

    public string transmissionFullName { get; set; }

    public string transmissionDescription { get; set; }

    public string easeOfDriving { get; set; }

    public string fuelEfficiencyImpact { get; set; }

    public string maintenanceCost { get; set; }

    public bool? isActiveTransmission { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}