// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Users
{
    public int userId { get; set; }

    public string fullName { get; set; }

    public string email { get; set; }

    public string phoneNumber { get; set; }

    public string userRole { get; set; }

    public string passwordHash { get; set; }

    public DateTime? createdDate { get; set; }

    public string username { get; set; }
}