// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class VehicleCategories
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public string CategoryIcon { get; set; }

    public string TypicalSeatingCapacity { get; set; }

    public string TypicalPriceRange { get; set; }

    public int? PopularityRank { get; set; }

    public bool? IsActiveCategory { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}