// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class VehicleCategories
{
    public int categoryId { get; set; }

    public string categoryName { get; set; }

    public string categoryDescription { get; set; }

    public string categoryIcon { get; set; }

    public string typicalSeatingCapacity { get; set; }

    public string typicalPriceRange { get; set; }

    public int? popularityRank { get; set; }

    public bool? isActiveCategory { get; set; }

    public virtual ICollection<CarListings> CarListings { get; set; } = new List<CarListings>();
}